Globals.OsType=WINDOWS

Globals.DbType=cubrid

#Globals.DriverClassName=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#Globals.Url=jdbc:log4jdbc:cubrid:218.158.115.10:40000:hslcbirthsys:::?charset=utf-8
#Globals.UserName=gioinfra
#Globals.Password=gioinfra214!